# Generated by Django 4.1 on 2022-10-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('region', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
