# Generated by Django 4.1 on 2022-10-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=1),
        ),
    ]
