# Generated by Django 4.1 on 2022-10-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_created',
            field=models.BooleanField(default=False),
        ),
    ]
