# Generated by Django 4.1 on 2022-10-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='region',
            field=models.CharField(choices=[('africa', 'Africa'), ('middle east', 'Middle East'), ('europe', 'Europe'), ('americas', 'Americas'), ('global', 'Global'), ('asia pacific', 'Asia Pacific')], default='Global', max_length=255),
        ),
    ]
