# Generated by Django 4.1 on 2022-10-27 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_footprint_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 27, 13, 44, 43, 398289)),
        ),
    ]
