# Generated by Django 4.1 on 2022-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_footprint_time_alter_footprint_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footprint',
            name='time',
        ),
        migrations.AddField(
            model_name='footprint',
            name='waktu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footprint',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
