# Generated by Django 4.1 on 2022-10-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_remove_footprint_time_footprint_waktu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footprint',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='footprint',
            old_name='waktu',
            new_name='datetime_show',
        ),
    ]
