# Generated by Django 4.1 on 2022-10-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_rename_date_footprint_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footprint',
            name='to_order',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
